# REDIS
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    # Redis服务器（默认服务器127.0.0.1）
    host: 127.0.0.1
    # Redis服务器连接端口（默认6379）
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000
    jedis:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: 100
        # 连接池中得最小空连接
        max-idle: 10
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: 10

  # 数据库连接
  datasource:
    # JDBC驱动得全限定类名。默认根据URL自动检测
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定JDBC得URL
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    # 指定数据库名
    username: root
    # 指定数据库密码
    password: root
    # 数据源类型
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  # 编著实体类位置
  type-aliases-package: com.springboot_redis.model
  # 标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  # 在控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设定应用的context-path
server:
  servlet:
    context-path: /springboot

  port: 8080